application: wdyt
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /[^\.]*(\?.+)*$
  script: main.application
  secure: optional

- url: /(.+)
  static_files: resources/\1
  upload: resources/(.+)
  secure: optional

libraries:
- name: webapp2
  version: "2.5.2"