application: destroytheproxy
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.html)
  mime_type: text/html
  static_files: destroy-the-proxy/\1
  upload: destroy-the-proxy/(.*\.html)

- url: /(.*\.css)
  mime_type: text/css
  static_files: destroy-the-proxy/\1
  upload: destroy-the-proxy/(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: destroy-the-proxy/\1
  upload: destroy-the-proxy/(.*\.js)

- url: /(.*\.(bmp|gif|jpeg|jpg|png))
  static_files: destroy-the-proxy/\1
  upload: destroy-the-proxy/(.*\.(bmp|gif|jpeg|jpg|png))

- url: /(.*\.ttf)
  static_files: destroy-the-proxy/\1
  upload: destroy-the-proxy/(.*\.(ttf|fon))

- url: /(.*\.(mp4|wma|ogg|m4a|mp3))
  static_files: destroy-the-proxy/\1
  upload: destroy-the-proxy/(.*\.(mp4|wma|ogg|m4a|mp3))

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest